# Generated by Django 5.0.6 on 2024-06-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="departments",
            fields=[
                (
                    "department_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "deparment_name",
                    models.CharField(
                        choices=[
                            ("Business Administration", "Business Administration"),
                            ("Civil Engineering", "Civil Engineering"),
                            ("Computer Science", "Computer Science"),
                            ("Electirical Engineering", "Electirical Engineering"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "Departments",
            },
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_number", models.PositiveIntegerField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("field_of_study", models.CharField(max_length=50)),
                ("gpa", models.FloatField(default=0.0)),
                ("register_date_time", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fk_Student_Department",
                        to="students.departments",
                    ),
                ),
            ],
            options={
                "db_table": "Students",
            },
        ),
    ]
