# Generated by Django 5.0.6 on 2024-06-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="department",
            table="department",
        ),
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
    ]
