# Generated by Django 5.0.6 on 2024-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_deparment_name_department_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=100),
        ),
    ]
